version: "3.7"

services:
  redis:
    container_name: redis-hangell-github
    image: redis
    ports: 
      - 6379:6379
  app:
    build: .
    container_name: api-hangell-github
    restart: always
    ports:
      - 3000:3000
    volumes:
     - .:/usr/app  
    links:
      - redis
    depends_on:
      - redis